controllers:
    resource: ../src/Controller/
    type: attribute

app_lucky_number:
    path: /lucky/number/{number}
    controller: App\Controller\LuckyController::number
    methods: GET
    condition:  "params['number'] == 10"